-- 001_create_agencies.sql
-- agencies

CREATE TABLE IF NOT EXISTS agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fr_agency_id BIGINT NOT NULL UNIQUE,
    raw_name TEXT NOT NULL,
    name TEXT NOT NULL,
    short_name TEXT,
    slug TEXT NOT NULL,
    description TEXT,
    url TEXT,
    json_url TEXT,
    parent_id BIGINT,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
