-- 003_create_policy_documents.sql
-- policy_documents

CREATE TABLE IF NOT EXISTS policy_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_entry_id BIGINT UNIQUE REFERENCES feed_entries(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_id TEXT NOT NULL,
    unique_key TEXT NOT NULL UNIQUE,
    document_number TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    agency TEXT,
    summary TEXT NOT NULL,
    keypoints JSONB,
    impact_score TEXT,
    political_score INTEGER,
    source_url TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    document_type TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_policy_documents_published_at ON policy_documents(published_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_documents_unique_key ON policy_documents(unique_key);
