-- 005_create_likes.sql
-- likes

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    feed_entry_id BIGINT NOT NULL REFERENCES feed_entries(id) ON DELETE CASCADE,
    value INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, feed_entry_id),
    CHECK (value IN (1, -1))
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes(user_id);
CREATE INDEX IF NOT EXISTS idx_likes_feed_entry_id ON likes(feed_entry_id);
CREATE INDEX IF NOT EXISTS idx_likes_feed_entry_id_value ON likes(feed_entry_id, value);
