-- 006_create_policy_document_sources.sql
-- policy_document_sources

CREATE TABLE IF NOT EXISTS policy_document_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL,
    external_id TEXT NOT NULL,
    raw_data JSONB NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    policy_document_id BIGINT NOT NULL REFERENCES policy_documents(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (source_key, external_id)
);

CREATE INDEX IF NOT EXISTS idx_policy_document_sources_policy_document_id ON policy_document_sources(policy_document_id);
