 -- 006_create_raw_policy_documents.sql
 -- raw_policy_documents

CREATE TABLE IF NOT EXISTS raw_policy_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL,
    external_id TEXT NOT NULL,
    raw_data JSONB NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    policy_document_id BIGINT NOT NULL REFERENCES policy_documents(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (source_key, external_id)
);

CREATE INDEX IF NOT EXISTS idx_raw_policy_documents_policy_document_id ON raw_policy_documents(policy_document_id);
