"""Add likes table

Revision ID: 212c9373ebfb
Revises: 2079c5a11595
Create Date: 2025-11-17 20:01:55.045906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212c9373ebfb'
down_revision: Union[str, None] = '2079c5a11595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('frarticle_id', sa.Integer(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['frarticle_id'], ['frarticles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'frarticle_id', name='uix_user_article_like')
    )
    op.create_index('idx_likes_frarticle_id', 'likes', ['frarticle_id'], unique=False)
    op.create_index('idx_likes_user_id', 'likes', ['user_id'], unique=False)
    op.create_index('idx_likes_user_positive', 'likes', ['user_id', 'is_positive'], unique=False)
    op.create_index(op.f('ix_likes_frarticle_id'), 'likes', ['frarticle_id'], unique=False)
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_frarticle_id'), table_name='likes')
    op.drop_index('idx_likes_user_positive', table_name='likes')
    op.drop_index('idx_likes_user_id', table_name='likes')
    op.drop_index('idx_likes_frarticle_id', table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
