"""Add political_leaning to users

Revision ID: fcfae4a45433
Revises: 212c9373ebfb
Create Date: 2025-11-18 06:33:15.079647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfae4a45433'
down_revision: Union[str, None] = '212c9373ebfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('political_leaning', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'political_leaning')
    # ### end Alembic commands ###
