package db

import (
	"database/sql"
	"fmt"
	"strings"
)

const MigrationSQL = `
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_superuser INTEGER NOT NULL DEFAULT 0,
    is_verified INTEGER NOT NULL DEFAULT 0,
    google_id TEXT UNIQUE,
    name TEXT,
    picture_url TEXT,
    political_leaning TEXT,
    state TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fr_agency_id BIGINT NOT NULL UNIQUE,
    raw_name TEXT NOT NULL,
    name TEXT NOT NULL,
    short_name TEXT,
    slug TEXT NOT NULL,
    description TEXT,
    url TEXT,
    json_url TEXT,
    parent_id BIGINT,
    raw_data TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS frarticles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    source_id TEXT NOT NULL,
    unique_key TEXT NOT NULL UNIQUE,
    document_number TEXT NOT NULL,
    raw_data TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    source_url TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    document_type TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    frarticle_id BIGINT NOT NULL REFERENCES frarticles(id) ON DELETE CASCADE,
    is_bookmarked INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, frarticle_id)
);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    frarticle_id BIGINT NOT NULL REFERENCES frarticles(id) ON DELETE CASCADE,
    is_liked INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, frarticle_id)
);

CREATE INDEX IF NOT EXISTS idx_frarticles_published_at ON frarticles(published_at);
CREATE INDEX IF NOT EXISTS idx_frarticles_unique_key ON frarticles(unique_key);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes(user_id);
`

func (db *DB) RunMigrations() error {
	tx, err := db.Begin()
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	statements := splitStatements(MigrationSQL)
	for _, stmt := range statements {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" {
			continue
		}
		if _, err := tx.Exec(stmt); err != nil {
			return fmt.Errorf("failed to run migration: %w", err)
		}
	}

	if err := db.addMissingColumns(tx); err != nil {
		return fmt.Errorf("failed to add missing columns: %w", err)
	}

	return tx.Commit()
}

func splitStatements(sql string) []string {
	var statements []string
	var current strings.Builder
	inSingleQuote := false
	inDoubleQuote := false
	inComment := false
	parens := 0

	for i := 0; i < len(sql); i++ {
		ch := sql[i]

		if inComment {
			if ch == '\n' {
				inComment = false
			}
			continue
		}

		if ch == '-' && i+1 < len(sql) && sql[i+1] == '-' {
			inComment = true
			i++
			continue
		}

		if ch == '\'' && !inDoubleQuote {
			inSingleQuote = !inSingleQuote
		}
		if ch == '"' && !inSingleQuote {
			inDoubleQuote = !inDoubleQuote
		}

		if !inSingleQuote && !inDoubleQuote {
			if ch == '(' {
				parens++
			}
			if ch == ')' {
				parens--
			}
		}

		if ch == ';' && parens == 0 && !inSingleQuote && !inDoubleQuote && !inComment {
			stmt := current.String()
			if strings.TrimSpace(stmt) != "" {
				statements = append(statements, stmt)
			}
			current.Reset()
		} else {
			current.WriteByte(ch)
		}
	}

	stmt := current.String()
	if strings.TrimSpace(stmt) != "" {
		statements = append(statements, stmt)
	}

	return statements
}

func (db *DB) addMissingColumns(tx *sql.Tx) error {
	var count int

	err := tx.QueryRow("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'frarticles' AND column_name = 'source'").Scan(&count)
	if err != nil {
		return err
	}
	if count == 0 {
		_, err = tx.Exec("ALTER TABLE frarticles ADD COLUMN source TEXT NOT NULL DEFAULT 'fedreg'")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}

		_, err = tx.Exec("ALTER TABLE frarticles ADD COLUMN source_id TEXT NOT NULL DEFAULT ''")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}

		_, err = tx.Exec("ALTER TABLE frarticles ADD COLUMN unique_key TEXT")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}

		_, err = tx.Exec("UPDATE frarticles SET source = 'fedreg', source_id = document_number, unique_key = 'fedreg:' || document_number WHERE source IS NULL OR source = ''")
		if err != nil {
			return fmt.Errorf("failed to backfill source columns: %w", err)
		}

		_, err = tx.Exec("CREATE UNIQUE INDEX IF NOT EXISTS idx_frarticles_unique_key ON frarticles(unique_key)")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return fmt.Errorf("failed to create unique_key index: %w", err)
		}
	}

	err = tx.QueryRow("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'frarticles' AND column_name = 'document_type'").Scan(&count)
	if err != nil {
		return err
	}
	if count == 0 {
		_, err = tx.Exec("ALTER TABLE frarticles ADD COLUMN document_type TEXT")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}
	}

	err = tx.QueryRow("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'frarticles' AND column_name = 'pdf_url'").Scan(&count)
	if err != nil {
		return err
	}
	if count == 0 {
		_, err = tx.Exec("ALTER TABLE frarticles ADD COLUMN pdf_url TEXT")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}
	}

	err = tx.QueryRow("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'state'").Scan(&count)
	if err != nil {
		return err
	}
	if count == 0 {
		_, err = tx.Exec("ALTER TABLE users ADD COLUMN state TEXT")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}
	}

	err = tx.QueryRow("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'agencies' AND column_name = 'raw_name'").Scan(&count)
	if err != nil {
		return err
	}
	if count == 0 {
		_, err = tx.Exec("ALTER TABLE agencies ADD COLUMN raw_name TEXT NOT NULL DEFAULT ''")
		if err != nil && !strings.Contains(err.Error(), "already exists") {
			return err
		}
	}

	return nil
}
